### ISSUE TITLE
Show Steam ID

### ISSUE THREAD

**Issue by entity** [TruckersMP/Steam-Socialite#11]
Hi,

Thanks for creating this integration, is there any chance you could extract the steam id / username from `profileurl` and show this inside of the response?

Thanks a ton

**Comment by bensherred** [comment]
Hi @heychazza,

I'm not 100% sure which response you are referring to, but you can access the users steam id by the `->getId()` method and their username by the `->getNickname()` method?

For more information on these, please have a look at the following documentation: https://laravel.com/docs/8.x/socialite#retrieving-user-details

**Comment by entity** [comment]
> Hi @heychazza,
> 
> I'm not 100% sure which response you are referring to, but you can access the users steam id by the `->getId()` method and their username by the `->getNickname()` method?
> 
> For more information on these, please have a look at the following documentation: https://laravel.com/docs/8.x/socialite#retrieving-user-details

Hi, when I looked (its been a while) this was their display name, not the actual ID (steamcommunity.com/user/**thisthing**)

**Comment by ShawnCZek** [comment]
Hello @heychazza,

Sorry for the late response. This completely slipped out of my mind.

Anyway, this library works in the same way as any other Steam Socialite provider does.
That means the `->user()` response is an instance of the `Laravel\Socialite\Two\User` class, where all the data is parsed and mapped.

If you wish to access the raw data, you can do so by using the raw collection like the following:

```php
$user = Socialite::driver('steam')->user();
$profileUrl = $user->getRaw()['profileurl'];
```

Is this what you meant?

**Comment by entity** [comment]
> Hello @heychazza,
> 
> 
> 
> Sorry for the late response. This completely slipped out of my mind.
> 
> 
> 
> Anyway, this library works in the same way as any other Steam Socialite provider does.
> 
> That means the `->user()` response is an instance of the `Laravel\Socialite\Two\User` class, where all the data is parsed and mapped.
> 
> 
> 
> If you wish to access the raw data, you can do so by using the raw collection like the following:
> 
> 
> 
> ```php
> 
> $user = Socialite::driver('steam')->user();
> 
> $profileUrl = $user->getRaw()['profileurl'];
> 
> ```
> 
> 
> 
> Is this what you meant?

Hey, no worries aha! It's been so long, so not something I need now. Thanks for the reply!
